export const projects=[
    {
        id: 4,
        photo: 'coolhotel.png',
        url: 'https://eurostarinn.com',
        title: 'EurostarInn Hotel',
        desc: 'The EurostarInn Hotel website, a product of my internship. Its sleek interface, intuitive navigation, and responsive design facilitate seamless exploration and booking, demonstrating my ability to deliver functional and visually appealing digital solutions.',
    },
    {
        id: 1,
        photo: 'weather-app.png',
        url: 'https://weather-vanilla-project.netlify.app/',
        title: 'Weather App',
        desc: 'The Weather App, using HTML, CSS, and JavaScript, delivers real-time weather data for major global cities. Users input a city name, and the app provides key weather information, including temperature, humidity, wind speed, and conditions, utilizing external APIs for accuracy.',
    },
    {
        id: 7,
        photo: 'resticious.png',
        url: 'https://resticious.vercel.app/',
        title: 'Resticious',
        desc: 'A Full-Stack restaurant management system featuring secure authentication, order placement and tracking, and comprehensive admin tools for user, product, and order management for Customers and Staffs',
    },
    {
        id: 0,
        photo: 'bg.png',
        url: 'https://bhagavadgeeta.vercel.app/',
        title: 'Bhagavad Gita',
        desc: `Explore Bhagavad Gita Website, a comprehensive platform enabling users to search, read, and delve into the profound verses and chapters of this timeless scripture. Immerse yourself in the teachings and gain insights into life's philosophical and spiritual aspects with user-friendly navigation and a rich repository of Gita verses.`,
    },
    {
        id: 2,
        photo: 'tenzies.png',
        url: 'https://lets-tenzy.netlify.app/',
        title: 'Tenzies Game',
        desc: 'Tenzies game offers a digital version of the classic dice game, Tenzi. Players roll virtual dice to match a chosen pattern and compete to get equal values in all the dices.',
    },
    {
        id: 3,
        photo: 'restaurant.png',
        url: 'https://restaurant-uiux.netlify.app/',
        title: 'Yummy Restaurant',
        desc: 'The Frontend UI/UX Project showcases an aesthetically pleasing restaurant interface with a focus on fresh ingredients. Its design seamlessly blends a vibrant, inviting look with user-friendly navigation, creating an immersive dining experience.',
    },
    {
        id: 5,
        photo: 'sorting-project.png',
        url: 'https://searching-sorting.vercel.app/',
        title: 'Sorting Project',
        desc: 'The Sorting App is a practical tool that not only efficiently sorts user-provided input but also calculates and displays the time taken to complete the sorting process. This feature-rich app aids users in understanding the performance of different sorting algorithms.',
    },
    {
        id: 6,
        photo: 'pokedex.png',
        url: 'https://pokedex-coolreact.netlify.app/',
        title: 'Pokedex',
        desc: 'The Pokedex App is a comprehensive tool for Pokemon enthusiasts. Users can easily search for specific Pokemon and view their details by clicking on individual cards. It offers an immersive experience, providing in-depth information about each Pokemon in a user-friendly interface.',
    },
]
